package actions

import (
	"errors"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/olegsobchuk/taxviewer/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Tax)
// DB Table: Plural (taxes)
// Resource: Plural (Taxes)
// Path: Plural (/taxes)
// View Template Folder: Plural (/templates/taxes/)

// TaxesResource is the resource for the Tax model
type TaxesResource struct {
	buffalo.Resource
}

// List gets all Taxes. This function is mapped to the path
// GET /taxes
func (v TaxesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	taxes := &models.Taxes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Taxes from the DB
	if err := q.All(taxes); err != nil {
		return err
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, taxes))
}

// Show gets the data for one Tax. This function is mapped to
// the path GET /taxes/{tax_id}
func (v TaxesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty Tax
	tax := &models.Tax{}

	// To find the Tax the parameter tax_id is used.
	if err := tx.Find(tax, c.Param("tax_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, tax))
}

// New renders the form for creating a new Tax.
// This function is mapped to the path GET /taxes/new
func (v TaxesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Tax{}))
}

// Create adds a Tax to the DB. This function is mapped to the
// path POST /taxes
func (v TaxesResource) Create(c buffalo.Context) error {
	// Allocate an empty Tax
	tax := &models.Tax{}

	// Bind tax to the html form elements
	if err := c.Bind(tax); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(tax)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, tax))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "tax.created.success"))
	// and redirect to the taxes index page
	return c.Render(201, r.Auto(c, tax))
}

// Edit renders a edit form for a Tax. This function is
// mapped to the path GET /taxes/{tax_id}/edit
func (v TaxesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty Tax
	tax := &models.Tax{}

	if err := tx.Find(tax, c.Param("tax_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, tax))
}

// Update changes a Tax in the DB. This function is mapped to
// the path PUT /taxes/{tax_id}
func (v TaxesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty Tax
	tax := &models.Tax{}

	if err := tx.Find(tax, c.Param("tax_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Tax to the html form elements
	if err := c.Bind(tax); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(tax)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, tax))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", T.Translate(c, "tax.updated.success"))
	// and redirect to the taxes index page
	return c.Render(200, r.Auto(c, tax))
}

// Destroy deletes a Tax from the DB. This function is mapped
// to the path DELETE /taxes/{tax_id}
func (v TaxesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.New("no transaction found")
	}

	// Allocate an empty Tax
	tax := &models.Tax{}

	// To find the Tax the parameter tax_id is used.
	if err := tx.Find(tax, c.Param("tax_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(tax); err != nil {
		return err
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", T.Translate(c, "tax.destroyed.success"))
	// Redirect to the taxes index page
	return c.Render(200, r.Auto(c, tax))
}
